M .Scripts/dunstbar  M .aliases  M .config/bspwm/bspwmrc  M .config/picom.conf  M .config/sxhkd/sxhkdrc

diff --git a/.config/bspwm/bspwmrc b/.config/bspwm/bspwmrc
--- a/.config/bspwm/bspwmrc
+++ b/.config/bspwm/bspwmrc
@@ -1,27 +1,14 @@
 #!/usr/bin/env bash
 
-#{{{ AUTOGAP
-autogap_settings() {
-   # gaps
-   export G0=5    # minimum gap size
-   export GS=5    # gaps size integer
-   export GN=4    # number of windows
-
-   # left and right padding
-   export PS=9    # padding size integer
-   export PN=2    # number of windows
-}
-#}}}
 #{{{ CONFIG
-config() {
-   printf '\e[33m%s...' "applying configs"
-
+config() { printf '\e[33m%s...' "applying configs"
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
 
    bspc config focused_border_color    "${color4}"
    bspc config presel_feedback_color   "${color4}"
    bspc config normal_border_color     "${color0}"
    bspc config border_width            2
+   #bspc config border_width            0
    bspc config gapless_monocle         true
 
    bspc config bottom_padding          0
@@ -36,9 +23,7 @@ config() {
    printf '\e[36m %s\n' "done."; }
 #}}}
 #{{{ RULES
-rules() {
-   printf '\n\e[33m%s...' "setting rules"
-
+rules() { printf '\n\e[33m%s...' "setting rules"
    bspc rule -r "*"
 
    bspc config external_rules_command "$(which external_rules)"
@@ -53,6 +38,20 @@ rules() {
    printf '\e[36m %s\n\n' "done."
 }
 #}}}
+
+#{{{ AUTOGAP
+autogap_settings() {
+   # gaps
+   export G0=5    # minimum gap size
+   export GS=5    # gaps size integer
+   export GN=4    # number of windows
+
+   # left and right padding
+   export PS=9    # padding size integer
+   export PN=2    # number of windows
+}
+#}}}
+
 #{{{ APPS
 apps() {
    for app in autogap dunstbar dunst acpid_events; do
@@ -61,31 +60,19 @@ apps() {
       app_is_running="$(ps ax | sed -n "/nvim/d;/sed/d;/\<$app\>/p")"
 
       if [[ "$app_is_running" ]]
-      then _restart $app
-      else _start $app
+      then _restart $app || printf '\e[31m%s: %s\n' "$app" "restart failed"
+      else _start $app || printf '\e[31m%s: %s\n' "$app" "failed"
       fi
 
    done
 }
 
-_restart(){
-   ukill "$1" 1>/dev/null &&
-      {
-         "$1" "${o[@]}" &>/dev/null & disown
-         printf '\e[33m%s: %s\n' "$1" "restarted"
-      } || {
-         printf '\e[31m%s: %s %s\n' "$1" "ukill" "failed"
-      }
-}
-
-_start(){
+_restart(){ ukill "$1" 1>/dev/null || return 1
    "$1" "${o[@]}" &>/dev/null & disown &&
-      {
-         printf '\e[37m%s: %s\n' "$1" "started"
-      } || {
-         printf '\e[31m%s: %s %s\n' "$1" "failed"
-      }
-}
+      printf '\e[33m%s: %s\n' "$1" "restarted"; }
+
+_start(){ "$1" "${o[@]}" &>/dev/null & disown || return 1
+   printf '\e[37m%s: %s\n' "$1" "started"; }
 #}}}
 #{{{ QUTEBROWSER
 qute(){
@@ -120,6 +107,7 @@ make_fifo(){
    done
 }
 #}}}
+
 #{{{ MAIN
 main(){
    xmodmap -e "keycode 135 = Super_R"
