M .Scripts/autogap  M .config/bspwm/bspwmrc
Former-commit-id: 0ece6a278b9c56c2767b4d25a8ae33efe53e8ded
Former-commit-id: 473cf2f95259f706b391921b44b11f1079baedfb

diff --git a/.config/bspwm/bspwmrc b/.config/bspwm/bspwmrc
--- a/.config/bspwm/bspwmrc
+++ b/.config/bspwm/bspwmrc
@@ -1,74 +1,41 @@
 #!/usr/bin/env bash
 
-#   _   _          ____                   __ _
-#  | | | |        |___ \                 / _(_)
-#  | |_| |__   ___  __) | ___ ___  _ __ | |_ _  __ _
-#  | __| '_ \ / _ \|__ < / __/ _ \| '_ \|  _| |/ _` |
-#  | |_| | | |  __/___) | (_| (_) | | | | | | | (_| |
-#   \__|_| |_|\___|____/ \___\___/|_| |_|_| |_|\__, |
-#                                               __/ |
-#                                              |___/
 
-config() {
-
-      printf '\e[33m%s...' "applying configs"
-
-   # -- BSPWM -- #
-
-      bspc config focused_border_color	"${color4}"
-      bspc config presel_feedback_color "${color4}"
-      bspc config normal_border_color	"${color0}"
-      bspc config border_width		2
-      bspc config gapless_monocle	true
-
-      bspc config bottom_padding 0
-      bspc config top_padding 0
-
-      bspc config center_pseudo_tiled 	true
-      bspc config split_ratio		0.60
-
-      bspc config initial_polarity	first_child
-      bspc config automatic_scheme	spiral
-
-      bspc monitor -d 1 2 3 4 5 6 7 8 9 10
-
-
-   # -- autogap -- #
-
-   # borders
-      #export BO=3
+autogap_settings() {
 
    # gaps
-      export GS=7	# gaps size integer
+      export GS=5	# gaps size integer
       export GN=4	# number of windows before $G0 gaps
 
    # left and right padding
-      export PS=7	# padding size integer
+      export PS=9	# padding size integer
       export PN=2	# number of windows before zero padding
 
+}
+
+config() { printf '\e[33m%s...' "applying configs"
+
+   bspc config focused_border_color	"${color4}"
+   bspc config presel_feedback_color "${color4}"
+   bspc config normal_border_color	"${color0}"
+   bspc config border_width		2
+   bspc config gapless_monocle	true
+
+   bspc config bottom_padding 0
+   bspc config top_padding 0
+
+   bspc config center_pseudo_tiled 	true
+   bspc config split_ratio		0.60
+
+   bspc config initial_polarity	first_child
+   bspc config automatic_scheme	spiral
+
+   bspc monitor -d 1 2 3 4 5 6 7 8 9 10
+
    printf '\e[36m %s\n' "done."
-}
-
-
-apps() {
-
-   for a in autogap dunstbar dunst acpid_events; do
-   case $a in dunstbar) o=(--boot);; *) o=(); esac
-
-      if [[ $(ps ax | sed -n "/sed/d;/\<$a\>/p") ]]; then
-	 ukill "$a" 1>/dev/null && {
-	    "$a" "${o[@]}" &>/dev/null & disown
-	    printf '\e[33m%s: %s\n' "$a" "restarted"
-	 } || printf '\e[31m%s: %s %s\n' "$a" "ukill" "failed"
-      else
-	 "$a" "${o[@]}" &>/dev/null & disown &&
-	 printf '\e[37m%s: %s\n' "$a" "started" ||
-	 printf '\e[31m%s: %s %s\n' "$a" "failed"
-      fi
-
-   done
 
 }
+
 
 rules() {
 
@@ -80,20 +47,52 @@ rules() {
 
    bspc rule -a Zathura state=tiled
    bspc rule -a float sticky=off state=floating 
-
    bspc rule -a gass sticky=on state=floating focus=off border=on
    bspc rule -a files layer=above locked=on sticky=on state=floating hidden=on
-
    bspc rule -a scratchterm layer=above locked=on sticky=on state=floating hidden=on
    bspc rule -a scratchmath layer=above locked=on sticky=on state=floating hidden=on
 
-   printf '\e[36m %s\n\n' "done."
+printf '\e[36m %s\n\n' "done."; }
+
+
+apps() {
+
+   for app in autogap dunstbar dunst acpid_events; do
+
+      case $app in dunstbar) o=(--boot);; *) o=(); esac
+
+      app_is_running="$(ps ax | sed -n "/sed/d;/\<$a\>/p")"
+
+      if [[ "$app_is_running" ]]
+      then _restart $app
+      else _start $app
+      fi
+
+   done
 
 }
 
+_restart(){
+   ukill "$1" 1>/dev/null &&
+      {
+         "$1" "${o[@]}" &>/dev/null & disown
+         printf '\e[33m%s: %s\n' "$1" "restarted"
+      } || {
+         printf '\e[31m%s: %s %s\n' "$1" "ukill" "failed"
+      }
+}
 
-qute() {
+_start(){
+   "$1" "${o[@]}" &>/dev/null & disown &&
+      {
+         printf '\e[37m%s: %s\n' "$1" "started"
+      } || {
+         printf '\e[31m%s: %s %s\n' "$1" "failed"
+      }
+}
 
+
+qute(){
    printf '\e[33m\n%s...' "linking files"
    ln -sf "$HOME/.cache/wal/dunstrc" "$HOME/.config/dunst/dunstrc" &
    ln -sf "$HOME/.cache/wal/zathurarc" "$HOME/.config/zathura/zathurarc" &
@@ -117,7 +116,7 @@ qute() {
 }
 
 
-main() {
+main(){
    xmodmap -e "keycode 135 = Super_R"
    source "$HOME/.cache/wal/colors.sh"
 
@@ -138,7 +137,11 @@ main() {
    done
    # ------------------- #
 
-   rules; config; qute; apps
+   config
+   rules
+   autogap_settings
+   qute
+   apps
 
 }
 
